spring:
    application:
        name: enrollment-service
    config:
        import: "optional:configserver:http://configserver:8089"
    profiles:
        active: dev
    cloud:
        config:
            uri: http://configserver:8089

resilience4j:
    circuitbreaker:
        instances:
            enrollmentService:
                register-health-indicator: true
                minimum-number-of-calls: 5
                permitted-number-of-calls-in-half-open-state: 3
                automatic-transition-from-open-to-half-open-enabled: true
                wait-duration-in-open-state: 5s
                failure-rate-threshold: 50
                record-exceptions:
                    - org.springframework.web.client.RestClientException
                    - java.io.IOException
                    - java.util.concurrent.TimeoutException
            userService:
                register-health-indicator: true
                minimum-number-of-calls: 5
                permitted-number-of-calls-in-half-open-state: 3
                automatic-transition-from-open-to-half-open-enabled: true
                wait-duration-in-open-state: 15s
                failure-rate-threshold: 60
            courseService:
                register-health-indicator: true
                minimum-number-of-calls: 5
                permitted-number-of-calls-in-half-open-state: 3
                automatic-transition-from-open-to-half-open-enabled: true
                wait-duration-in-open-state: 15s
                failure-rate-threshold: 60


resilience4j.ratelimiter:
    instances:
        rateLimiterEnrollmentService:
            limit-for-period: 5
            limit-refresh-period: 5000
            timeout-duration: 1000ms

resilience4j.retry:
    instances:
        retryEnrollmentService:
            max-attempts: 5
            wait-duration: 10000
            retry-exceptions:
                - java.util.concurrent.TimeoutException

resilience4j.bulkhead:
    instances:
        bulkheadEnrollmentService:
            max-wait-duration: 2ms
            max-concurrent-calls: 20

# resilience4j.thread-pool-bulkhead:
#     instances:
#         bulkheadEnrollmentService:
#             max-thread-pool-size: 1
#             core-thread-pool-size: 1
#             queue-capacity: 1


management:
    endpoints:
        web:
            exposure:
                include: "*"
    endpoint:
        health:
            show-details: always
            show-components: always
    health:
        circuitbreakers:
            enabled: true
    tracing:
        sampling:
            probability: 1.0
        enabled: true
