spring:
    application:
     name: gateway-server 
    cloud:
        config: 
            uri: http://configserver:8071

logging:
  level:
    com.netflix: WARN
    org.springframework.web: WARN
    com.elearning: DEBUG
            
management:
  tracing:
    sampling:
      probability: 1.0
    enabled: true
  endpoints:
    web:
      exposure:
        include: health,metrics,prometheus
