version: "3.8"

services:
  # PostgreSQL for User Service

  # PostgreSQL for Enrollment Service
  enrollmentdb:
    image: postgres:latest
    container_name: enrollmentdb
    ports:
      - "5435:5432"
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev
      POSTGRES_DB: enrollmentservice_db
    volumes:
      - ./sql/init_enrollment.sql:/docker-entrypoint-initdb.d/1-init_enrollment.sql
      - ./sql/data_enrollment.sql:/docker-entrypoint-initdb.d/2-data_enrollment.sql
    networks:
      backend:
        aliases:
          - "enrollmentdb"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dev -d enrollmentservice_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Config Server
  configserver:
    build:
      context: "../configserver"
      dockerfile: Dockerfile
      args:
        JAR_FILE: target/configserver-0.0.1-SNAPSHOT.jar
    image: elearning/configserver:0.0.1-SNAPSHOT
    container_name: configserver
    ports:
      - "8089:8089"
    environment:
      SERVER_PORT: "8089"
      GITHUB_USERNAME: "Nicholas-Bava"
      GITHUB_PASSWORD: "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"
    networks:
      backend:
        aliases:
          - "configserver"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8089/"]
      interval: 10s
      timeout: 5s
      retries: 5

  # User Service


  # Enrollment Service
  enrollmentservice:
    build:
      context: "../enrollment-service"
      dockerfile: Dockerfile
      args:
        JAR_FILE: target/enrollment-service-0.0.1-SNAPSHOT.jar
    image: elearning/enrollmentservice:0.0.1-SNAPSHOT
    container_name: enrollmentservice

    environment:
      SPRING_APPLICATION_NAME: enrollment-service
      SPRING_PROFILES_ACTIVE: dev
      SPRING_CONFIG_IMPORT: "optional:configserver:http://configserver:8089/"
      CONFIGSERVER_URI: "http://configserver:8089"
      CONFIGSERVER_PORT: "8089"
      SPRING_DATASOURCE_URL: jdbc:postgresql://enrollmentdb:5432/enrollmentservice_db
      SPRING_DATASOURCE_USERNAME: dev
      SPRING_DATASOURCE_PASSWORD: dev
      GITHUB_USERNAME: "Nicholas-Bava"
      GITHUB_PASSWORD: "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"
    ports:
      - "8083:8080"
    depends_on:
      enrollmentdb:
        condition: service_healthy
      configserver:
        condition: service_started
    networks:
      backend:
        aliases:
          - "enrollmentservice"

networks:
  backend:
    driver: bridge
