spring:
  application:
    name: config-server
  profiles:
    active:
    - native
  cloud:
    config:
      server:
        git:
          uri: https://github.com/ihuaylupo/config.git
          searchPaths: licensingservice
    
server:
  port: 8071


#Enable all Spring Boot Actuator endpoints.
management:
  endpoints:
    web:
      exposure:
        include: "*"