spring:
    application:
      name: user-service
    config:
      import: "optional:configserver:http://configserver:8089"
    profiles:
      active: dev
    cloud:
        config: 
            uri: http://configserver:8089